version: "3.9"

services:
  db:
    image: postgres:15
    container_name: booking_db
    env_file:
      - .env-non-dev
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:

    image: redis:7
    container_name: booking_redis

  booking:
    image: booking_image
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: booking_app
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_started
    command: ["/booking/docker/app.sh"]
    ports:
      - 7777:8000

  celery:
    image: booking_celery
    build:
      context: .
    container_name: booking_celery
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    command: ["/booking/docker/celery.sh", "celery"]
  flower:
    image: booking_flower
    build:
      context: .
    container_name: booking_flower
    env_file:
      - .env-non-dev
    command: [ "/booking/docker/celery.sh", "flower" ]
    depends_on:
      - redis